name: Deploy hibernate-types Maven artifact

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/maven-deploy-hibernate-types.yml
      - hibernate-types/**

jobs:
  deploy:
    uses: wrk-fmd/mls-packages/.github/workflows/maven-deploy.yml@main
    with:
      directory: hibernate-types
    secrets:
      token: ${{ secrets.MLS_PACKAGES_TOKEN }}
