name: Deploy mls-parent Maven artifact

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/maven-deploy-parent.yml
      - parent/**

defaults:
  run:
    working-directory: parent

jobs:
  deploy:
    uses: wrk-fmd/mls-packages/.github/workflows/maven-deploy.yml@main
    with:
      directory: parent
    secrets:
      token: ${{ secrets.MLS_PACKAGES_TOKEN }}
